profiles:
  name: dev

spring:
  jpa:
    database: MySQL
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto=update: update

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atmmachin
    username: root
    password: Harika@02
    initialization-mode: always
